#! /bin/bash
read -p "Enter the name of the database: " dbName
read -p "Enter the basepath to the import files, leave empty for [$PWD]: " importPath
  if [[ $importPath == "" ]]; then
    importPath=$PWD;
  fi
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
importScript=`cat "${DIR}/sqlite3.sql"`

# get the basepath
basepath=$PWD

# Allows changes such as Prefixes for tables in the script.
# importScript=$(echo $importScript | sed -e "s#@BASEPATH@#$basepath#g")
# importScript=$(echo $importScript | sed -e "s/@TABLEPREFIX@/$tblPrefix/g")

# importScript="create table n (id INTEGER PRIMARY KEY,f TEXT,l TEXT);insert into n (f,l) values ('john','smith');"

echo
echo Creating the database structure:
sqlite3 $dbName "$importScript";

echo
echo Creating temporary files:
 echo ".mode tabs" > /tmp/sqlite3init.cat
 echo ".import \"${importPath}/distribution.txt\" Distribution" >> /tmp/sqlite3init.cat
 echo ".import \"${importPath}/reference.txt\" Reference" >> /tmp/sqlite3init.cat
 echo ".import \"${importPath}/taxa.txt\" Taxon" >> /tmp/sqlite3init.cat
 echo ".import \"${importPath}/vernacular.txt\" VernacularName" >> /tmp/sqlite3init.cat
 
echo
echo Importing the data:
cat /tmp/sqlite3init.cat | sqlite3 $dbName 

echo
echo Removing temporary files:
rm /tmp/sqlite3init.cat

echo
echo Import completed.
