#! /bin/bash
read -p "Enter the name of the database: " dbName
read -p "Enter the basepath to the import files, leave empty for [$PWD]: " importPath
  if [[ $importPath == "" ]]; then
    importPath=$PWD;
  fi
echo Configuring the import script
importScript=`cat sqlite3.sql`

# get the basepath
basepath=$PWD

# Allows changes such as Prefixes for tables in the script.
# importScript=$(echo $importScript | sed -e "s#@BASEPATH@#$basepath#g")
# importScript=$(echo $importScript | sed -e "s/@TABLEPREFIX@/$tblPrefix/g")

# importScript="create table n (id INTEGER PRIMARY KEY,f TEXT,l TEXT);insert into n (f,l) values ('john','smith');"

sqlite3 $dbName "$importScript";

echo ".mode tabs" > sqlite3init.cat
echo ".import $importPath/distribution.txt Distribution" >> sqlite3init.cat
echo ".import $importPath/reference.txt Reference" >> sqlite3init.cat
echo ".import $importPath/taxa.txt Taxon" >> sqlite3init.cat
echo ".import $importPath/vernacular.txt VernacularName" >> sqlite3init.cat

cat sqlite3init.cat | sqlite3 $dbName 

