#! /bin/bash
read -p "Enter the name of the database: " dbName
read -p "Enter the basepath to the import files, leave empty for [$PWD]: " importPath
  if [[ $importPath == "" ]]; then
    importPath=$PWD;
  fi
echo Configuring the import script
importScript=`cat sqlite3.sql`

# get the basepath
basepath=$PWD

sqlite3 $dbName "$importScript";

# echo $importScript

cat /tmp/test.sql | sqlite3 $dbName 

# sqlite3 $dbName '.mode csv' 
# sqlite3 $dbName '.header on'
# sqlite3 $dbName '.separator "\t"'
# sqlite3 $dbName ".import $importPath/distribution.txt Distribution"
# sqlite3 $dbName ".import $importPath/reference.txt Reference"
# sqlite3 $dbName ".import $importPath/taxa.txt Taxon"
# sqlite3 $dbName ".import $importPath/vernacular.txt VernacularName"

