<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" 
         xmlns:md="eml://ecoinformatics.org/methods-2.1.1" 
         xmlns:proj="eml://ecoinformatics.org/project-2.1.1" 
         xmlns:d="eml://ecoinformatics.org/dataset-2.1.1" 
         xmlns:res="eml://ecoinformatics.org/resource-2.1.1" 
         xmlns:dc="http://purl.org/dc/terms/" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.0/eml.xsd" 
         packageId="http://ipt.gbif.org/resource.do?id=col_gsd_metadata/v1" 
         system="http://gbif.org" 
         scope="system" 
         xml:lang="eng">
    <dataset>
        <title xml:lang="eng">
            [title]
        </title>
        <creator>
            <organizationName>
                Catalog Of Life secretariat
            </organizationName>
            <address>
                <city>
                    Reading
                </city>
                <country>
                    GB
                </country>
            </address>
            <onlineUrl>
                http://www.catalogueoflife.org
            </onlineUrl>
        </creator>
        <metadataProvider>
            <organizationName>
                Catalog Of Life secretariat
            </organizationName>
            <address>
                <city>
                    Reading
                </city>
                <country>
                    GB
                </country>
            </address>
            <onlineUrl>
                http://www.catalogueoflife.org
            </onlineUrl>
        </metadataProvider>
        <pubDate>
            [pubDate]
        </pubDate>
        <language>
            eng
        </language>
        <abstract>
            <para>
                [abstract]
            </para>
        </abstract>
        <distribution scope="document">
            <online>
                <url function="information">
                    [sourceUrl]
                </url>
            </online>
        </distribution>
        <coverage>
            <taxonomicCoverage>
                [taxonomicCoverage]
            </taxonomicCoverage>
        </coverage>
        <contact>
            <individualName>
                <surName>
                    [contact]
                </surName>
            </individualName>
            <organizationName>
                [organizationName] 
            </organizationName>
            <address>
                <city>
                    [contactCity]
                </city>
                <country>
                    [contactCountry]
                </country>
            </address>
        </contact>
    </dataset>
    <additionalMetadata>
        <metadata>
            <gbif>
                <dateStamp>
                    [dateStamp]
                </dateStamp>
                <hierarchyLevel>
                    dataset
                </hierarchyLevel>
                <resourceLogoUrl>
                    [resourceLogoUrl]
                </resourceLogoUrl>
            </gbif>
            <sourceDatabase>
                <abbreviatedName>
                    [abbreviatedName]
                </abbreviatedName>
                <authorsAndEditors>
                    [authorsEditors]
                </authorsAndEditors>
                <version>
                    [version]
                </version>
            </sourceDatabase>
            <statistics>
                <numberOfSpecies>
                    [numberOfSpecies]
                </numberOfSpecies>
                <numberOfInfraspecies>
                    [numberOfInfraspecies]
                </numberOfInfraspecies>
                <numberOfSynonyms>
                    [numberOfSynonyms]
                </numberOfSynonyms>
                <numberOfCommonNames>
                    [numberOfCommonNames]
                </numberOfCommonNames>
                <totalNumber>
                    [totalNumber]
                </totalNumber>
            </statistics>
        </metadata>
    </additionalMetadata>
</eml:eml>